# Generated by Django 4.1.4 on 2022-12-24 14:04

from django.db import migrations, models
import django.db.models.deletion
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(max_length=150, upload_to='products/images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('full_title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('language', models.CharField(choices=[('uzb/rus', 'Uzb Rus'), ('uzb', 'Uzb'), ('rus', 'Rus'), ('cyr', 'Cyr'), ('eng', 'Eng')], default='uzb', max_length=15)),
                ('volume', models.PositiveIntegerField()),
                ('format', models.CharField(choices=[('60x84 1/32', 'Format 01'), ('60x90 1/32', 'Format 02'), ('70x90 1/32', 'Format 03'), ('70x100 1/32', 'Format 04'), ('70x108 1/32', 'Format 05'), ('75x90 1/32', 'Format 06'), ('84x108 1/32', 'Format 07'), ('60x84 1/16', 'Format 08'), ('60x90 1/16', 'Format 09'), ('70x90 1/16', 'Format 10'), ('70x100 1/16', 'Format 11'), ('70x108 1/16', 'Format 12'), ('75x90 1/16', 'Format 13'), ('84x108 1/16', 'Format 14')], default='60x84 1/32', max_length=15)),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('cover', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft')], default='hard', max_length=15)),
                ('info', models.JSONField(blank=True, decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='products.category')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
            },
        ),
    ]
